version: "3"
services:
    crm-parceiro-service:
        build:
            context: .
            dockerfile: ./docker/app.dockerfile
        image: aeroespacial-site:latest
        container_name: aeroespacial-site-container
        command: gunicorn -w 2 'server.web:app' -b '0.0.0.0:5000'
        restart: on-failure
        # command: flask run --host=0.0.0.0 --port=5000 --debug
        # ports:
        #     - 5000:5000
        environment:
            - AMBIENTE=dev
            # - LOG_LEVEL=DEBUG
        volumes:
            - crmstatic-volume:/home/non-root/client/public
        networks:
            - aeroespacial-network

    crmnginx-service:
        build:
            context: .
            dockerfile: ./docker/nginx.dockerfile
        image: nginx:latest
        container_name: nginx-container
        restart: on-failure
        ports:
            - 8080:80
        environment:
            - NGINX_WORKERS=2
            - NGINX_ACCEPT_MUTEX=true
            - NGINX_SERVER_APP=aeroespacial-service:5000
            - NGINX_ACCESS_LOG=off
            - NGINX_STATIC_FOLDER=/usr/share/nginx/html/static
            - NGINX_TIMEOUT=300
        networks:
            - aeroespacial-network
        volumes:
            - crmstatic-volume:/usr/share/nginx/html/static
        depends_on:
            - aeroespacial-service

    aeroespacial-service:
        image: redis:7.2.0-alpine3.18
        container_name: aeroespacial-container
        restart: on-failure
        # ports:
        #     - "6379:6379"
        networks:
            - aeroespacial-network

volumes:
    crmstatic-volume:

networks:
    aeroespacial-network:
        name: aeroespacial-network
        external: true
