version: "3"
services:
  aeroespacial-site-service:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    image: 806324789387.dkr.ecr.sa-east-1.amazonaws.com/dev/aeroespacial/aeroespacial:latest
    container_name: aeroespacial-container
    command: gunicorn -w 2 'server.web:app' -b '0.0.0.0:5000'
    restart:
      on-failure
      # command: flask run --host=0.0.0.0 --port=5000 --debug
    ports:
      - 5000:5000
    environment:
      - AMBIENTE=dev
      - AWS_ACCESS_KEY_ID=${HOST_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${HOST_AWS_SECRET_ACCESS_KEY}
      - APP_SESSION_URL=redis://aeroespacial-redis-service:6379/0
      - APP_BROKER_URL=redis://aeroespacial-redis-service:6379/1
      - APP_BACKEND_URL=redis://aeroespacial-redis-service:6379/1
      - APP_CACHE_URL=redis://aeroespacial-redis-service:6379/2
      # - LOG_LEVEL=DEBUG
    volumes:
      - aeroespacial-static-volume:/home/non-root/client/public
    networks:
      - aeroespacial-network
    depends_on:
      - aeroespacial-redis-service

  aeroespacial-worker-service:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    image: 806324789387.dkr.ecr.sa-east-1.amazonaws.com/dev/aeroespacial/aeroespacial:latest
    container_name: aeroespacial-worker-container
    command: celery -A server.worker worker --concurrency=2 -B --loglevel=ERROR -E
    restart: on-failure
    environment:
      - AMBIENTE=dev
      - AWS_ACCESS_KEY_ID=${HOST_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${HOST_AWS_SECRET_ACCESS_KEY}
      # - APP_SESSION_URL=redis://aeroespacial-redis-service:6379/0
      - APP_BROKER_URL=redis://aeroespacial-redis-service:6379/1
      - APP_BACKEND_URL=redis://aeroespacial-redis-service:6379/1
      - APP_CACHE_URL=redis://aeroespacial-redis-service:6379/2
      # - LOG_LEVEL=DEBUG
    networks:
      - aeroespacial-network
    depends_on:
      - aeroespacial-redis-service

  aeroespacial-nginx-service:
    build:
      context: .
      dockerfile: ./docker/nginx.dockerfile
    image: 806324789387.dkr.ecr.sa-east-1.amazonaws.com/dev/nginx:latest
    container_name: aeroespacial-nginx-container
    restart: on-failure
    ports:
      - 8080:80
    environment:
      - NGINX_WORKERS=2
      - NGINX_ACCEPT_MUTEX=on
      - NGINX_SERVER_APP=aeroespacial-site-service:5000
      - NGINX_ACCESS_LOG=off
      - NGINX_STATIC_FOLDER=/usr/share/nginx/html/static
      - NGINX_TIMEOUT=300
    networks:
      - aeroespacial-network
    volumes:
      - aeroespacial-static-volume:/usr/share/nginx/html/static
    depends_on:
      - aeroespacial-site-service

  aeroespacial-redis-service:
    image: redis:7.2.0-alpine3.18
    container_name: aeroespacial-redis-container
    restart: on-failure
    # ports:
    #     - "6379:6379"
    networks:
      - aeroespacial-network

volumes:
  aeroespacial-static-volume:
    name: aeroespacial-static-volume

networks:
  aeroespacial-network:
    name: aeroespacial-network
    external: false
