version: 0
services:
  - name: aeroespacial-site-service
    type: web
    envVars:
      - key: AMBIENTE
        value: dev
      - key: APP_SESSION_URL
        value: redis://aeroespacial-redis-service:6379/0
      - key: APP_BROKER_URL
        value: redis://aeroespacial-redis-service:6379/1
      - key: APP_BACKEND_URL
        value: redis://aeroespacial-redis-service:6379/1
      - key: APP_CACHE_URL
        value: redis://aeroespacial-redis-service:6379/2
    disk:
      name: aeroespacial-static-volume
    plan: starter
  - name: aeroespacial-worker-service
    type: worker
    envVars:
      - key: AMBIENTE
        value: dev
      - key: APP_BROKER_URL
        value: redis://aeroespacial-redis-service:6379/1
      - key: APP_BACKEND_URL
        value: redis://aeroespacial-redis-service:6379/1
      - key: APP_CACHE_URL
        value: redis://aeroespacial-redis-service:6379/2
    plan: starter
  - name: aeroespacial-nginx-service
    type: web
    envVars:
      - key: NGINX_WORKERS
        value: "2"
      - key: NGINX_ACCEPT_MUTEX
        value: on
      - key: NGINX_SERVER_APP
        value: aeroespacial-site-service:5000
      - key: NGINX_ACCESS_LOG
        value: off
      - key: NGINX_STATIC_FOLDER
        value: /usr/share/nginx/html/static
      - key: NGINX_TIMEOUT
        value: "300"
    disk:
      name: aeroespacial-static-volume
    plan: starter
  - name: aeroespacial-redis-service
    type: web
    plan: small
