version: 0
services:
  - name: aeroespacial-site-service
    type: web
    envVars:
      AMBIENTE: dev
      APP_SESSION_URL: redis://aeroespacial-redis-service:6379/0
      APP_BROKER_URL: redis://aeroespacial-redis-service:6379/1
      APP_BACKEND_URL: redis://aeroespacial-redis-service:6379/1
      APP_CACHE_URL: redis://aeroespacial-redis-service:6379/2
    disk:
      name: aeroespacial-static-volume
    plan: starter
  - name: aeroespacial-worker-service
    type: job
    envVars:
      AMBIENTE: dev
      APP_BROKER_URL: redis://aeroespacial-redis-service:6379/1
      APP_BACKEND_URL: redis://aeroespacial-redis-service:6379/1
      APP_CACHE_URL: redis://aeroespacial-redis-service:6379/2
    plan: starter
  - name: aeroespacial-nginx-service
    type: web
    envVars:
      NGINX_WORKERS: 2
      NGINX_ACCEPT_MUTEX: on
      NGINX_SERVER_APP: aeroespacial-site-service:5000
      NGINX_ACCESS_LOG: off
      NGINX_STATIC_FOLDER: /usr/share/nginx/html/static
      NGINX_TIMEOUT: 300
    disk:
      name: aeroespacial-static-volume
    plan: starter
  - name: aeroespacial-redis-service
    type: cache
    plan: small
