services:
  - name: aeroespacial-site-service # Name of the service
    image: aeroespacial:latest # Image to use (from Docker Hub or a registry)
    # Define environment variables, build commands, ports, etc. as needed

  - name: aeroespacial-worker-service
    image: aeroespacial:latest # Same image for this service
    # Define environment variables, commands, etc.

  - name: aeroespacial-nginx-service
    image: aeroespacial/nginx:latest
    # Define environment variables, ports, volumes, etc.

  - name: aeroespacial-redis-service
    image: redis:7.2.0-alpine3.18
    # Define environment variables, if any

# Define volumes if needed (check Render's documentation for syntax)

# Define a single-container web service to route traffic to aeroespacial-nginx-service
web:
  name: aeroespacial-web
  ports:
    - 80:80
  env:
    # Define any environment variables needed for the web service
  # Define relationships between services if necessary
